# Generated by Django 4.1.1 on 2022-10-15 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlistings_bids_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='auctionlistings',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listingOwner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bids',
            name='bidAmount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bids',
            name='bidderUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bidder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='image_url',
            field=models.URLField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='starting_bid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingStartingBid', to='auctions.bids'),
        ),
        migrations.AlterField(
            model_name='auctionlistings',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listingCategory', to='auctions.categories'),
        ),
    ]
