# Generated by Django 4.1.1 on 2022-10-20 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_categories_auctionlistings_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuctionListings',
            new_name='AuctionListing',
        ),
        migrations.RenameModel(
            old_name='Bids',
            new_name='Bid',
        ),
        migrations.RenameModel(
            old_name='Categories',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
